network:
  renderer: networkd
  ethernets:
    ens33:
      addresses:
        - 192.168.100.10/24
      nameservers:
        addresses: [8.8.8.8,8.8.4.4,192.168.100.10]
      routes:
        - to: default
          via: 192.168.100.2